language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - "pip install -r requirements-dev.txt"
  - "pip install ."
script: py.test src/geventhttpclient/tests

jobs:
  include:
    - stage: build
      sudo: required
      services:
        - docker
      os: linux
      python: "3.6"
      install:
        - pip install cibuildwheel==0.8.0
      script:
        - cibuildwheel --output-dir wheelhouse
        # Upload to PyPI on tags
        - if [ "${TRAVIS_TAG:-}" != "" ]; then
            pip install twine;
            python -m twine upload --skip-existing wheelhouse/*;
          fi
      env:
        - CIBW_SKIP=cp33
    - stage: build
      sudo: required
      os: osx
      osx_image: xcode8.3
      language: null
      python: null
      install:
        # Python 3 is needed to run cibuildwheel
        - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then
            brew update;
            brew upgrade python;
          fi
        - pip install cibuildwheel==0.8.0
      script:
        - cibuildwheel --output-dir wheelhouse
        # Upload to PyPI on tags
        - if [ "${TRAVIS_TAG:-}" != "" ]; then
            pip install twine;
            python -m twine upload --skip-existing wheelhouse/*;
          fi
      env:
        - CIBW_SKIP=cp33
